### ISSUE TITLE
Master Issue

### ISSUE THREAD

**Issue by SamuelBeshara** [Sampler-Capstone/Sampler#3]
### Front End
- [ ] Listen Page (Yuki)
- [ ] Home Page
- [ ] Production Page
  - [ ] Pads Component 
  - [ ] Knobs component
  - [ ] Volume component
  - [ ] Show Wave of song (Ric)

### Backend
- [ ] Pads
  - [ ] Receiving input from HW 
  - [ ] Assigning a track to Pad
- [ ] Knobs
  - [ ] Receiving input from HW
  - [ ] Assigning a sound effect to Pad
- [ ] Producing (Sam)
- [ ] Recording (Sam)
- [ ] Playback tracks (#5)
- [x] Slicing (Sam)
